name: Docker Image CI

on:
  push:
    branches: [ "master", "release/" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build securelib image
      run: docker build . --file Dockerfile --tag securelib:$(date +%s)

